= Fusion Cloud Native on Kubernetes

This repo contains scripts for installing Fusion 5.x on Kubernetes

== Google Kubernetes Engine (GKE)

Run the `setup_f5_gke.sh` script to install Fusion 5.x in a GKE cluster.

See: https://doc.lucidworks.com/fusion-server/5.0/deployment/kubernetes/how-to-deploy-gke.html for more information on deploying Fusion 5 on GKE.

== Other Kubernetes Platforms

If you're not running on GKE, you can use Helm to install the Fusion chart to an existing Kubernetes cluster.

=== Choose a Release Name and Namespace

Choose a unique release name for Fusion, such as `f5`; Helm uses a release name to track a specific installation of an application in the cluster.

You also need to choose the Kubernetes namespace to install Fusion. You can install multiple instances of Fusion in the cluster in separate namespaces.
However, do not install more than one Fusion release in the same namespace.

=== Customize Fusion Chart Settings

Fusion aims to be well-configured out-of-the-box, but you can customize any of the built-in settings using a custom values yaml file.
To begin, copy the example file provided in this repo:
```
cp customize_fusion_values.yaml.example <release>_<namespace>_fusion_values.yaml
```
where `<release>` is the name you give to your Fusion release, such as `f5` and `<namespace>` is the Kubernetes namespace where you want to install Fusion, such as `default`.

=== Use Helm to Install Fusion

After making changes to the custom values yaml file, install Fusion using the following commands:

```
RELEASE=f5
NAMESPACE=default

helm repo add lucidworks https://charts.lucidworks.com
helm repo update
helm install --timeout 240 --namespace "${NAMESPACE}" -n "${RELEASE}" lucidworks/fusion --values "${RELEASE}_${NAMESPACE}_fusion_values.yaml"
kubectl rollout status deployment/${RELEASE}-api-gateway --timeout=600s --namespace "${NAMESPACE}"
```

For more information, please see the Fusion documentation: https://doc.lucidworks.com/fusion-server/5.0/deployment/kubernetes/index.html
