= Fusion Cloud Native on Kubernetes

This repo contains scripts for installing Fusion 5.x on Kubernetes

== Google Kubernetes Engine (GKE)

Run the `setup_f5_gke.sh` script to install Fusion 5.x in a GKE cluster.

See: https://doc.lucidworks.com/fusion-server/5.0/deployment/kubernetes/how-to-deploy-gke.html for more information on deploying Fusion 5 on GKE.

== Other Kubernetes Platforms

Lucidworks provides a Helm chart for Fusion 5.x, so if you're not running on GKE, you can simply do:

=== Customize Fusion Chart Settings

Fusion aims to be well-configured out-of-the-box but you can customize any of the built-in settings using a custom values yaml file.

```
cp customize_fusion_values.yaml.example <release>_<namespace>_fusion_values.yaml
```
where `<release>` is the name you give to your Fusion release, such as `f5` and `<namespace>` is the Kubernetes namespace where you want to install Fusion, such as `default`.

After making changes to the yaml file, install Fusion using the following commands:

```
RELEASE=f5
NAMESPACE=default
helm repo add lucidworks https://charts.lucidworks.com
helm repo update
helm install --timeout 240 --namespace "${NAMESPACE}" -n "${RELEASE}" lucidworks/fusion --values "${RELEASE}_${NAMESPACE}_fusion_values.yaml"
kubectl rollout status deployment/${RELEASE}-api-gateway --timeout=600s --namespace "${NAMESPACE}"
```

For more information, please see the Fusion documentation: https://doc.lucidworks.com/fusion-server/5.0/deployment/kubernetes/index.html
