{
 "title": "JVM Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(system_cpu_usage{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(system_cpu_usage{kubernetes_namespace=~\"$namespace\",app_kubernetes_io_component=~\".+\"},app_kubernetes_io_component)"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Process CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{action}}"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "classes/sec" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_classes_loaded_classes{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "allocation rate" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name,id)(rate(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\", area=\"heap\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}} {{id}}"
    }
   ]
  },
  {
   "title": "Heap Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\", area=\"heap\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{id}} Memory"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\", state=\"runnable\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{state}} Threads"
    },
    {
     "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", app_kubernetes_io_component=~\"$service\", state=\"blocked\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{state}} Threads"
    }
   ]
  }
 ]
}