{
 "title": "Solr Node Dashboard",
 "description": "Solr Dashboard 2",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Kube kubernetes_namespace",
    "query": "label_values(solr_collections_shard_state{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$kubernetes_namespace\", zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$kubernetes_namespace\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{kubernetes_namespace=~\"$kubernetes_namespace\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{kubernetes_namespace=~\"$kubernetes_namespace\", zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$kubernetes_namespace\", base_url=~\".+\"},base_url)"
   },
   {
    "name": "core",
    "query": "label_values(solr_metrics_core_requests_total{kubernetes_namespace=~\"$kubernetes_namespace\", base_url=~\"$base_url\"},core)"
   }
  ]
 },
 "panels": [
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_time_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_client_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_server_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_timeouts_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_cores{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Core Root File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Thread Pool Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_thread_pool_completed_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Submitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_thread_pool_submitted_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_running{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_connections{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{item}}"
    }
   ]
  }
 ]
}