{
 "title": "Docker Host & Container Overview",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(container_cpu_load_average_10s, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total, namespace)"
   },
   {
    "name": "name",
    "label": "Container Name",
    "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name!=\"POD\"}, container_name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",id=\"/\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} sent"
    }
   ]
  },
  {
   "title": "Total Running Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$node\",namespace=~\"$namespace\",container_name=~\"$name\"}[$interval]))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=~\"$node\",container=~\"$name\"}[$interval])) by (pod_name,instance) * 100",
     "legendFormat": "{{instance}} / {{pod_name}}"
    }
   ]
  },
  {
   "title": "Free Filesystem Space",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{kubernetes_node=~\"$node\"}) by (kubernetes_node, fstype)",
     "legendFormat": "{{kubernetes_node}} / {{fstype}}"
    }
   ]
  },
  {
   "title": "Available Memory on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"}",
     "legendFormat": "{{kubernetes_node}}"
    },
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[$interval])) by (kubernetes_node,device) > 0",
     "legendFormat": "OUT on {{kubernetes_node}}/{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[$interval])) by (kubernetes_node,device) > 0",
     "legendFormat": "IN on {{kubernetes_node}}/{{device}}"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",container_name=~\"$name\",name=~\".+\"}[$interval])) by (pod, container_name) * 100",
     "legendFormat": "{{pod}} / {{container_name}}"
    }
   ]
  },
  {
   "title": "System Load on Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{kubernetes_node=~\"$node\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container Interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node\",namespace=~\"$namespace\"}[$interval])) by (pod_name, container_name, interface)",
     "legendFormat": "{{pod_name}} / {{container_name}} / {{interface}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$node\",namespace=~\"$namespace\",container_name=~\"$name\",name=~\".+\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",name=~\".+\"}[$interval])",
     "legendFormat": "{{pod_name}} {{container_name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$node\",namespace=~\"$namespace\",container_name=~\"$name\",name=~\".+\"}) by (pod_name, container_name)",
     "legendFormat": "{{pod_name}} / {{container_name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(prometheus_build_info) by (version)",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "sum(node_exporter_build_info) by (version)",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "sum(cadvisor_version_info)by(dockerVersion)",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    {
     "expr": "sum(cadvisor_version_info)by(osVersion)",
     "legendFormat": "Host OS Version: {{osVersion}}"
    },
    {
     "expr": "sum(cadvisor_version_info)by(kernelVersion)",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}