{
 "title": "Solr Core Metrics",
 "description": "Solr Dashboard 2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Kube Namespace",
    "query": "label_values(solr_collections_shard_state{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$namespace\", zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$namespace\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{kubernetes_namespace=~\"$namespace\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{kubernetes_namespace=~\"$namespace\", zk_host=~\"$zk_host\",collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$namespace\", base_url=~\".+\"},base_url)"
   },
   {
    "name": "core",
    "query": "label_values(solr_metrics_core_requests_total{kubernetes_namespace=~\"$namespace\", base_url=~\"$base_url\"},core)"
   }
  ]
 },
 "panels": [
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{kubernetes_namespace=~\"$namespace\", base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{core}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Field Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_field_cache_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{base_url=~\"$base_url\",core=~\"$core\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$base_url\",core=~\"$core\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  }
 ]
}