{
 "title": "Gateway Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Kubernetes kubernetes_namespace",
    "query": "label_values(http_server_requests_seconds_count{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Requests per minute by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome, uri)(increase(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Gateway RPS by route",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (routeId,httpStatusCode,httpMethod,routeUri)(rate(gateway_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}[1m]))",
     "legendFormat": "{{httpStatusCode}} {{httpMethod}} {{routeId}}"
    }
   ]
  },
  {
   "title": "Log Message Rate (msg/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(irate(logback_events_total{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}[5m]))",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "HTTP Request Metrics (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"}",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Log Messages (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(logback_events_total{kubernetes_namespace=\"$kubernetes_namespace\",app_kubernetes_io_component=\"api-gateway\"})",
     "legendFormat": "{{level}} messages"
    }
   ]
  }
 ]
}