{
 "title": "Solr System Dashboard",
 "description": "Solr Dashboard 2",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Kube Namespace",
    "query": "label_values(solr_collections_shard_state{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$namespace\", zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{kubernetes_namespace=~\"$namespace\", base_url=~\".+\"},base_url)"
   }
  ]
 },
 "panels": [
  { "title": "Jetty Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{method}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_response_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{status}}"
    }
   ]
  },
  {
   "title": "Dispatches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_dispatches_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}}"
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{pool}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Count (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(solr_metrics_jvm_gc_total{kubernetes_namespace=\"$namespace\", base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Time (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_seconds_total{kubernetes_namespace=\"$namespace\", base_url=~\"$base_url\"}[1m])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Non-Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_non_heap_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_pools_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{space}} {{item}}"
      }
     ]
    },
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_threads{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_load_average{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  }
 ]
}