{
 "title": "Query Pipeline Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Kubernetes kubernetes_namespace",
    "query": "label_values(http_server_requests_seconds_count{kubernetes_namespace=~\".+\"},kubernetes_namespace)"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "kubernetes_pod_name",
    "query": "label_values(query_stage_outcome_total{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\".+\",pipelineId!~\"_lw_tmp_.*\"},kubernetes_pod_name)"
   },
   {
    "name": "stage",
    "label": "Stage Type",
    "query": "label_values(query_stage_outcome_total{kubernetes_namespace=~\"$kubernetes_namespace\",stageType=~\".+\",pipelineId!~\"_lw_tmp_.*\"},stageType)"
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(query_stage_outcome_total{kubernetes_namespace=~\"$kubernetes_namespace\",pipelineId=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pipelineId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",app_kubernetes_io_component=\"query-pipeline\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "RPS by kubernetes_pod_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name)(increase(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",app_kubernetes_io_component=\"query-pipeline\"}[1m]))/60"
    }
   ]
  },
  { "title": "Pipelines and Stages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "p99 Pipeline Execution Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p50 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p75 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p95 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Query Stage p99 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p95 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p75 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p50 Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage Execution Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_stage_outcome_total{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}) by (error, pipelineId, stageType)",
     "legendFormat": "{{pipelineId}} {{stageType}} (error {{error}})"
    }
   ]
  },
  {
   "title": "Stages per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_stage_outcome_total{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])) by (error, pipelineId, stageType)",
     "legendFormat": "{{pipelineId}} {{stageType}} runs per minute"
    }
   ]
  },
  { "title": "Solr Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "p99 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, le)(rate(solr_api_call_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])))"
    }
   ]
  },
  {
   "title": "Solr API Call Rate by Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorCode,host)(rate(solr_api_call_total{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\",}[1m]))",
     "legendFormat": "{{host}} (error={{errorCode}})"
    },
    {}
   ]
  },
  {
   "title": "p75 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(host, le)(rate(solr_api_call_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])))"
    }
   ]
  },
  {
   "title": "p95 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(host, le)(rate(solr_api_call_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])))"
    }
   ]
  },
  {
   "title": "p50 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(host, le)(rate(solr_api_call_time_secs_bucket{kubernetes_namespace=~\"$kubernetes_namespace\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m])))"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "RPS by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome, uri, kubernetes_pod_name)(rate(http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"query-pipeline\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Metrics (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"query-pipeline\"}",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  { "title": "Logging and Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Log Message Rate (msg/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(irate(logback_events_total{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"query-pipeline\"}[5m]))",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Log Messages (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(logback_events_total{kubernetes_namespace=\"$kubernetes_namespace\",app_kubernetes_io_component=\"query-pipeline\"})",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Jetty Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jetty_threads_current{kubernetes_namespace=~\"$kubernetes_namespace\",app_kubernetes_io_component=\"query-pipeline\"}",
     "legendFormat": "{{kubernetes_pod_name}} max threads"
    }
   ]
  }
 ]
}