{
 "title": "Solr Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(solr_metrics_core_errors_total, kubernetes_namespace)"
   },
   {
    "name": "url",
    "label": "Solr URL",
    "query": "label_values(solr_metrics_core_errors_total, base_url)"
   },
   {
    "name": "collection",
    "label": "Collection",
    "query": "label_values(solr_metrics_core_errors_total, collection)"
   },
   {
    "name": "core",
    "label": "Core",
    "query": "label_values(solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\"},core)"
   },
   { "name": "period", "label": "Period", "query": "5m,10m,15m,30m,1h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",item=\"systemCpuLoad\"}",
       "legendFormat": "CPU Load [{{base_url}}]"
      }
     ]
    },
    {
     "title": "Document Index Rate by Collection (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(base_url,collection)(rate(solr_metrics_core_searcher_documents{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",item=\"numDocs\"}[$period]))",
       "legendFormat": "{{base_url}} ({{collection}})"
      }
     ]
    },
    {
     "title": "Collection Sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Operations per minute (1m rate)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(solr_metrics_core_distrib_one_minute_rate{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"}*60)",
       "legendFormat": "{{collection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Heap Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",item=\"used\"}",
       "legendFormat": "{{base_url}}"
      }
     ]
    },
    {
     "title": "GC time per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (base_url,item)(rate(solr_metrics_jvm_gc_seconds_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\"}[$period])*60)",
       "legendFormat": "{{base_url}} ({{item}})"
      }
     ]
    },
    {
     "title": "GC per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(base_url,item)(rate(solr_metrics_jvm_gc_total{kubernetes_namespace=~\"$namespace\", base_url=~\"$url\"}[$period])*60)\n",
       "legendFormat": "{{base_url}} ({{item}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Cores (only some filtered by collection)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Operations per minute (1m rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(solr_metrics_core_distrib_one_minute_rate{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"}*60)",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Replication Generations per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(rate(solr_metrics_core_replication_generation{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"}[$period])*60)",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Timeouts per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(rate(solr_metrics_core_timeouts_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"}[$period])*60)",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Documents Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(core,collection)(solr_metrics_core_searcher_documents{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"})",
     "legendFormat": "{{core}} ({{collection}})"
    }
   ]
  },
  {
   "title": "Document Change Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(rate(solr_metrics_core_searcher_documents{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"}[$period])*60)",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Search Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(core)(solr_metrics_core_searcher_cache_hit_ratio{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"})",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "tlog replay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(solr_metrics_core_tlog_replay{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"})",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "tlog replay remaining bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(core)(solr_metrics_core_tlog_replay_rem_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"})",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Sizes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(solr_metrics_core_index_size_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Remaining tlog replay data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (collection)(solr_metrics_core_tlog_replay_rem_bytes{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Document Index Rate by Collection (per minute, by collection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(rate(solr_metrics_core_searcher_documents{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\",item=\"numDocs\"}[$period])*60)",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Errors per second (by collection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(rate(solr_metrics_core_server_errors_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"}[5m]))",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Operations per minute (1m rate, by collection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(solr_metrics_core_distrib_one_minute_rate{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"}*60)",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Timeouts per Minute (by collection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(collection)(rate(solr_metrics_core_timeouts_total{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"}[$period])*60)",
       "legendFormat": "{{collection}}"
      }
     ]
    },
    {
     "title": "Search Cache Hit Ratio (by collection)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg by(collection)(solr_metrics_core_searcher_cache_hit_ratio{kubernetes_namespace=~\"$namespace\",base_url=~\"$url\",core=~\"$core\",collection=~\"$collection\"})",
       "legendFormat": "{{collection}}"
      }
     ]
    }
   ]
  }
 ]
}