{
 "title": "Kube Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{namespace=~\".+\"},namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, namespace)(kube_pod_container_info{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "Active Cron Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cronjob, namespace)(kube_cronjob_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Node Allocatable Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}