{
 "title": "Templating Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=~\".+\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(zone_render_outcome_total{namespace=~\"$namespace\",pod=~\".+\"},pod)"
    }
   },
   {
    "name": "template",
    "label": "Template",
    "query": {
     "query": "label_values(zone_render_outcome_total{namespace=~\"$namespace\",templateId=~\".+\"},templateId)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(zone_render_outcome_total{namespace=~\"$namespace\",appId=~\".+\"},appId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",component=\"templating\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "RPS by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",component=\"templating\"}[1m]))/60"
    }
   ]
  },
  { "title": "Templates and Zones (By App)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "p99 Template Trigger and Render Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p95 Template Trigger and Render Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(appId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p75 Template Trigger and Render Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(appId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p50 Template Trigger and Render Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(appId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Zone p99 Render Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Zone p95 Render Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(appId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Zone p75 Render Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(appId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Zone p50 Render Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(appId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Zone Render Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zone_render_outcome_total{namespace=\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}) by (error, appId)",
     "legendFormat": "{{appId}} (error {{error}})"
    }
   ]
  },
  {
   "title": "Zones Rendered per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  by (error, appId)(increase(zone_render_outcome_total{namespace=\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m]))",
     "legendFormat": "{{appId}} renders per minute"
    }
   ]
  },
  {
   "title": "Templates and Zones (By Template)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "p99 Template Trigger and Render Time (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(templateId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "p95 Template Trigger and Render Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(templateId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "p75 Template Trigger and Render Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(templateId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "p50 Template Trigger and Render Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(templateId, le)(rate(template_trigger_render_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "Zone p99 Render Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(templateId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "Zone p95 Render Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(templateId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "Zone p75 Render Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(templateId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "Zone p50 Render Times (histogram)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(templateId, le)(rate(zone_render_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
       "legendFormat": "{{templateId}}"
      }
     ]
    },
    {
     "title": "Zone Render Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zone_render_outcome_total{namespace=\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}) by (error, templateId)",
       "legendFormat": "{{templateId}} (error {{error}})"
      }
     ]
    },
    {
     "title": "Zones Rendered per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum  by (error, templateId)(increase(zone_render_outcome_total{namespace=\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m]))",
       "legendFormat": "{{templateId}} renders per minute"
      }
     ]
    }
   ]
  },
  { "title": "Template Triggering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "p99 Template Trigger Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(appId, le)(rate(template_trigger_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p95 Template Trigger Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(appId, le)(rate(template_trigger_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p75 Template Trigger Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(appId, le)(rate(template_trigger_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "p50 Template Trigger Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(appId, le)(rate(template_trigger_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",appId=~\"$app\",templateId=~\"$template\"}[1m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  { "title": "Query Profile Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Query Profile Call Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorCode,queryProfile)(rate(query_profile_call_total{namespace=~\"$namespace\",pod=~\"$pod\",}[1m]))",
     "legendFormat": "{{queryProfile}} (error={{errorCode}})"
    },
    {}
   ]
  },
  {
   "title": "p99 Query Profile Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(queryProfile, le)(rate(query_profile_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])))"
    }
   ]
  },
  {
   "title": "p95 Query Profile Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(queryProfile, le)(rate(query_profile_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])))"
    }
   ]
  },
  {
   "title": "p75 Query Profile Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(queryProfile, le)(rate(query_profile_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])))"
    }
   ]
  },
  {
   "title": "p50 Query Profile Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(queryProfile, le)(rate(query_profile_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\"}[1m])))"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "RPS by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome, uri, kubernetes_pod)(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"templating\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Metrics (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"templating\"}",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  { "title": "Logging and Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Log Message Rate (msg/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(irate(logback_events_total{namespace=~\"$namespace\",component=\"templating\"}[5m]))",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Log Messages (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(logback_events_total{namespace=\"$namespace\",component=\"templating\"})",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Jetty Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jetty_threads_current{namespace=~\"$namespace\",component=\"templating\"}",
     "legendFormat": "{{pod}} max threads"
    }
   ]
  }
 ]
}