{
 "title": "Indexing Service Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=~\".+\"},namespace)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline Id",
    "query": {
     "query": "label_values(indexing_stage_process_time_secs_sum{namespace=~\"$namespace\",pipelineId=~\".+\"},pipelineId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Execution Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId)(increase(indexing_pipeline_outcome_total{namespace=~\"$namespace\", pipelineId=~\"$pipeline\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pipeline Execution Time (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId, le)(histogram_quantile(0.99, rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))     "
    }
   ]
  },
  {
   "title": "Pipeline Execution Time (p50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId, le)(histogram_quantile(0.50, rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))     "
    }
   ]
  },
  {
   "title": "p75 Stage Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId,stageType,stageId,le)(rate(indexing_stage_process_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))",
     "legendFormat": "{{pipelineId}}({{stageType}}) {{stageId}}"
    },
    {}
   ]
  },
  {
   "title": "p50 Stage Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(pipelineId,stageType,stageId,le)(rate(indexing_stage_process_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))",
     "legendFormat": "{{pipelineId}}({{stageType}}) {{stageId}}"
    },
    {}
   ]
  },
  {
   "title": "p99 Stage Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId,stageType,stageId,le)(rate(indexing_stage_process_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))",
     "legendFormat": "{{pipelineId}}({{stageType}}) {{stageId}}"
    },
    {}
   ]
  },
  {
   "title": "p95 Stage Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId,stageType,stageId,le)(rate(indexing_stage_process_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))",
     "legendFormat": "{{pipelineId}}({{stageType}}) {{stageId}}"
    }
   ]
  },
  {
   "title": "Indexed Document Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId)(increase(indexing_docs_in_total{namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Solr Indexing Time (p99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(indexing_solr_index_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))"
    }
   ]
  },
  {
   "title": "Solr Indexing Time (p50)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(pipelineId, le)(rate(indexing_solr_index_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))"
    }
   ]
  },
  {
   "title": "Solr Indexing Time (p95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(indexing_solr_index_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))"
    }
   ]
  },
  {
   "title": "Solr Indexing Time (p75)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(indexing_solr_index_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$pipeline\"}[1m])))"
    }
   ]
  }
 ]
}