{
 "title": "Gateway Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=~\".+\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"api-gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"api-gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests per minute by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome, uri)(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"api-gateway\"}[1m]))",
     "legendFormat": "{{uri}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Gateway RPS by route",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (routeId,httpStatusCode,httpMethod,routeUri)(rate(gateway_requests_seconds_count{namespace=~\"$namespace\",component=\"api-gateway\"}[1m]))",
     "legendFormat": "{{httpStatusCode}} {{httpMethod}} {{routeId}}"
    }
   ]
  },
  {
   "title": "Log Message Rate (msg/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(irate(logback_events_total{namespace=~\"$namespace\",component=\"api-gateway\"}[5m]))",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "HTTP Request Metrics (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{namespace=~\"$namespace\",component=\"api-gateway\"}",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Log Messages (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(logback_events_total{namespace=\"$namespace\",component=\"api-gateway\"})",
     "legendFormat": "{{level}} messages"
    }
   ]
  }
 ]
}