apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-log4j-config"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: log4j
data:
  log4j2.yaml: |
    Configuration:
      status: INFO
      monitorInterval: 30
      name: pulsar
      packages: io.prometheus.client.log4j2

      Properties:
        Property:
          - name: "pulsar.log.dir"
            value: "logs"
          - name: "pulsar.log.file"
            value: "pulsar.log"
          - name: "pulsar.log.appender"
            value: "RoutingAppender"
          - name: "pulsar.log.root.level"
            value: "debug"
          - name: "pulsar.log.level"
            value: "info"
          - name: "pulsar.routing.appender.default"
            value: "Console"

      # Example: logger-filter script
      Scripts:
        ScriptFile:
          name: filter.js
          language: JavaScript
          path: ./conf/log4j2-scripts/filter.js
          charset: UTF-8

      Appenders:

        # Console
        Console:
          name: Console
          target: SYSTEM_OUT
          PatternLayout:
            Pattern: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'} [%t] %-5level %logger{36} - %msg%n"

        # Rolling file appender configuration
        RollingFile:
          name: RollingFile
          fileName: "${sys:pulsar.log.dir}/${sys:pulsar.log.file}"
          filePattern: "${sys:pulsar.log.dir}/${sys:pulsar.log.file}-%d{MM-dd-yyyy}-%i.log.gz"
          immediateFlush: false
          PatternLayout:
            Pattern: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'} [%t] %-5level %logger{36} - %msg%n"
          Policies:
            TimeBasedTriggeringPolicy:
              interval: 1
              modulate: true
            SizeBasedTriggeringPolicy:
              size: 1 GB
          # Delete file older than 30days
          DefaultRolloverStrategy:
            Delete:
              basePath: ${sys:pulsar.log.dir}
              maxDepth: 2
              IfFileName:
                glob: "*/${sys:pulsar.log.file}*log.gz"
              IfLastModified:
                age: 30d

        Prometheus:
          name: Prometheus

        # Routing
        Routing:
          name: RoutingAppender
          Routes:
            pattern: "$${ctx:function}"
            Route:
              -
                Routing:
                  name: InstanceRoutingAppender
                  Routes:
                    pattern: "$${ctx:instance}"
                    Route:
                      -
                        RollingFile:
                          name: "Rolling-${ctx:function}"
                          fileName : "${sys:pulsar.log.dir}/functions/${ctx:function}/${ctx:functionname}-${ctx:instance}.log"
                          filePattern : "${sys:pulsar.log.dir}/functions/${sys:pulsar.log.file}-${ctx:instance}-%d{MM-dd-yyyy}-%i.log.gz"
                          PatternLayout:
                            Pattern: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'} [%t] %-5level %logger{36} - %msg%n"
                          Policies:
                            TimeBasedTriggeringPolicy:
                              interval: 1
                              modulate: true
                            SizeBasedTriggeringPolicy:
                              size: "20MB"
                            # Trigger every day at midnight that also scan
                            # roll-over strategy that deletes older file
                            CronTriggeringPolicy:
                              schedule: "0 0 0 * * ?"
                          # Delete file older than 30days
                          DefaultRolloverStrategy:
                            Delete:
                              basePath: ${sys:pulsar.log.dir}
                              maxDepth: 2
                              IfFileName:
                                glob: "*/${sys:pulsar.log.file}*log.gz"
                              IfLastModified:
                                age: 30d
                      - ref: "${sys:pulsar.routing.appender.default}"
                        key: "${ctx:function}"
              - ref: "${sys:pulsar.routing.appender.default}"
                key: "${ctx:function}"

      Loggers:

        # Default root logger configuration
        Root:
          level: "${sys:pulsar.log.root.level}"
          additivity: true
          AppenderRef:
            - ref: "${sys:pulsar.log.appender}"
              level: "${sys:pulsar.log.level}"
            - ref: Prometheus
              level: info

        Logger:
          - name: org.apache.bookkeeper.bookie.BookieShell
            level: info
            additivity: false
            AppenderRef:
              - ref: Console

          - name: verbose
            level: info
            additivity: false
            AppenderRef:
              - ref: Console