= Example App - Querying / Indexing in Fusion using JWT

For optimal performance in Fusion, high-frequency calls to the REST API
should use JSON Web Token (JWT) Authentication. The alternative to JWT is HTTP Basic Authentication, but this
puts strain on Fusion due to the cost of computing the hash. This strain results in worsened
querying and indexing performance and higher resource usage by Fusion.

Thus, HTTP Basic Authentication should *NOT* be used for high-frequency scenarios.

This app shows how to use Fusion REST APIs with JWT. Examples are provided for various HTTP client libraries.

== JWT Client Authentication Flow

. Get a JWT using the `/oauth2/token` endpoint.
. Save the JWT.
. Schedule the JWT to be refreshed before the expiration time of the current JWT. Repeat this every time a new JWT
is obtained.
. Use the saved JWT to issue requests to Fusion REST APIs.

== Running the Example
The following java system properties are used by the examples. System properties should be passed as JVM args like `-Dname=value`,
NOT program arguments. In IntelliJ these would be specified in the "VM options" field for
the run configuration.

- apiUrl - Required. URL to reach the Fusion API, for example `http://fusionhostname:6764`
- user - Required. Username to use to authenticate with Fusion API
- password - Required. Password to use to authenticate with Fusion API
- appId - Required unless queryUrl is specified. ID of the app to issue queries against, like "MyApp"
- search - Optional. Search terms to use against the default query profile, should be URL encoded like "tv+remotes"
- intervalMillis - Optional. Milliseconds to wait between queries, for example 1000 (for 1 second)
- queryUrl - Optional. By default, the example issues queries against the app's main query profile. This overrides
the url and causes the appId and search properties to be ignored. For example: "/api/links"

Run the desired class via your IDE, specifying the desired values for these as system properties in your run configuration.

For example, to run this in IntelliJ, your "VM options" field might look like this:
```
-DapiUrl=https://fusionhostname:6764 -Duser=admin -Dpassword=password123 -DintervalMillis=1000 -DappId=MyApp
```
