{
 "title": "Customer Dashboard v2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   },
   {
    "name": "namespace",
    "label": "Fusion Installation",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   },
   {
    "name": "queryPipelineId",
    "label": "Query Pipeline",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{namespace=~\"$namespace\", pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   },
   {
    "name": "indexPipelineId",
    "label": "Indexing Pipeline",
    "query": {
     "query": "query_result(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\", pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fusion Gateway RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",routeId=\"apps_qp\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Query Route RPS"
    },
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Global RPS"
    }
   ]
  },
  {
   "title": "Gateway Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",outcome=\"SERVER_ERROR\",routeId=\"apps_qp\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Query Error Rate"
    },
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{namespace=~\"$namespace\",outcome=\"SERVER_ERROR\",routeId=~\"(indexing|indexing_apps)\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Indexing Error Rate"
    }
   ]
  },
  {
   "title": "Query RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",uri=\"/query/{id}\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Query Pipeline Requests Per Second"
    }
   ]
  },
  {
   "title": "Indexing RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",cluster=~\"$cluster\",uri=~\"/api/v1/(index-pipelines|index.*)/(.*)\",method=\"POST\"}[1m]))",
     "legendFormat": "Indexing Requests Per Second"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Pipeline RPS (with outcomes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome)(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",cluster=~\"$cluster\",uri=~\"/query/{id}\"}[1m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Query Pipeline RPS By Pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pipelineId)(rate(pipeline_execution_duration_secs_count{namespace=~\"$namespace\",cluster=~\"$cluster\",pipelineId!~\"_lw_tmp_.*\",pipelineId=~\"$queryPipelineId\"}[1m]))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p95 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",cluster=~\"$cluster\",pipelineId!~\"_lw_tmp_.*\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p99 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",cluster=~\"$cluster\",pipelineId!~\"_lw_tmp_.*\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p50 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",cluster=~\"$cluster\",pipelineId!~\"_lw_tmp_.*\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p75 Query Pipeline Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",cluster=~\"$cluster\",pipelineId!~\"_lw_tmp_.*\",pipelineId=~\"$queryPipelineId\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Indexing Service RPS (non-GET)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"fusion-indexing\",method!=\"GET\"}[1m]))"
      }
     ]
    },
    {
     "title": "Document Index Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum by(pipelineId)(rate(indexing_docs_in_total{namespace=~\"$namespace\",job=\"fusion-indexing\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m]))\n",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p99 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p95 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p75 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    },
    {
     "title": "p50 Index Pipeline Execution Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(indexing_pipeline_exec_time_secs_bucket{namespace=~\"$namespace\",pipelineId=~\"$indexPipelineId\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
       "legendFormat": "{{pipelineId}}"
      }
     ]
    }
   ]
  }
 ]
}