{
 "title": "Kube Metrics (GMP)",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, namespace)(kube_pod_container_info{namespace=~\"$namespace\",cluster=~\"$cluster\"})",
     "legendFormat": "{{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "Active Cron Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cronjob, namespace)(kube_cronjob_status_active{namespace=~\"$namespace\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node Allocatable Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node)(kube_node_status_allocatable_memory_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}