{
 "title": "Load Balancer Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "query_result(rate(query_stage_outcome_total{pipelineId!~\"_lw_tmp_.*\"}[1m]))"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "query_result(rate(loadbalancing_googleapis_com:https_request_count{monitored_resource=\"https_lb_rule\"}[1h]))"
    }
   },
   {
    "name": "projectId",
    "label": "projectId",
    "query": {
     "query": "query_result(rate(loadbalancing_googleapis_com:https_request_count{monitored_resource=\"https_lb_rule\"}[1h]))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load balancer backend QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (backend_name)(rate(loadbalancing_googleapis_com:https_request_count{monitored_resource=\"https_lb_rule\",project_id=\"$projectId\",backend_target_name=~\"$backend\"}[${__interval}]))",
     "legendFormat": "{{backend_name}}"
    }
   ]
  },
  {
   "title": "Query Rate by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (response_code_class)(rate(loadbalancing_googleapis_com:https_request_count{monitored_resource=\"https_lb_rule\",project_id=\"$projectId\",backend_target_name=~\"$backend\"}[${__interval}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum by (backend_name, le)(increase(loadbalancing_googleapis_com:https_total_latencies_bucket{monitored_resource=\"https_lb_rule\",backend_target_name=~\"$backend\"}[${__interval}])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by (backend_name, le)(increase(loadbalancing_googleapis_com:https_total_latencies_bucket{monitored_resource=\"https_lb_rule\",backend_target_name=~\"$backend\"}[${__interval}])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p75 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75,sum by (backend_name, le)(increase(loadbalancing_googleapis_com:https_total_latencies_bucket{monitored_resource=\"https_lb_rule\",backend_target_name=~\"$backend\"}[${__interval}])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum by (backend_name, le)(increase(loadbalancing_googleapis_com:https_total_latencies_bucket{monitored_resource=\"https_lb_rule\",backend_target_name=~\"$backend\"}[${__interval}])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}