{
 "title": "Query Pipeline Metrics (GMP-test)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=~\".+\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pod)"
    }
   },
   {
    "name": "stage",
    "label": "Stage Type",
    "query": {
     "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",stageType=~\".+\",pipelineId!~\"_lw_tmp_.*\"},stageType)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(query_stage_outcome_total{namespace=~\"$namespace\",pipelineId=~\".+\",pipelineId!~\"_lw_tmp_.*\"},pipelineId)"
    }
   },
   {
    "name": "cluster",
    "label": "K8s Cluster",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{cluster=~\".+\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "RPS by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod)(increase(http_server_requests_seconds_count{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "Pipelines and Stages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "p99 Pipeline Execution Time (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p50 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p75 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "p95 Pipeline Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(pipelineId, le)(rate(pipeline_execution_duration_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}}"
    }
   ]
  },
  {
   "title": "Query Stage p99 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p95 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p75 Execution Times (histogram)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage p50 Execution Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(stageType, pipelineId, le)(rate(query_stage_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "{{pipelineId}} {{stageType}}"
    }
   ]
  },
  {
   "title": "Query Stage Execution Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}) by (error, pipelineId, stageType)",
     "legendFormat": "{{pipelineId}} {{stageType}} (error {{error}})"
    }
   ]
  },
  {
   "title": "Stages per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_stage_outcome_total{namespace=~\"$namespace\",pod=~\"$pod\",pipelineId=~\"$pipeline\",pipelineId!~\"_lw_tmp_.*\",cluster=~\"$cluster\"}[1m])) by (error, pipelineId, stageType)",
     "legendFormat": "{{pipelineId}} {{stageType}} runs per minute"
    }
   ]
  },
  {
   "title": "Solr Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Solr API Call Rate by Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorCode,host)(rate(solr_api_call_total{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "{{host}} (error={{errorCode}})"
    },
    {}
   ]
  },
  {
   "title": "p99 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, le)(rate(solr_api_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m])))"
    }
   ]
  },
  {
   "title": "p95 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(host, le)(rate(solr_api_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m])))"
    }
   ]
  },
  {
   "title": "p75 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(host, le)(rate(solr_api_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m])))"
    }
   ]
  },
  {
   "title": "p50 Solr API Call Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(host, le)(rate(solr_api_call_time_secs_bucket{namespace=~\"$namespace\",pod=~\"$pod\",cluster=~\"$cluster\"}[1m])))"
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (outcome, uri, pod)(rate(http_server_requests_seconds_count{namespace=~\"$namespace\",cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Request Metrics (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Logging and Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Message Rate (msg/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(irate(logback_events_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Log Messages (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(logback_events_total{namespace=~\"$namespace\",cluster=~\"$cluster\"})",
     "legendFormat": "{{level}} messages"
    }
   ]
  },
  {
   "title": "Jetty Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jetty_threads_current{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}} max threads"
    }
   ]
  }
 ]
}