---
# These minimal values files are valid with fusion version:
# 5.3.0 - 5.3.5

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fusion-installer
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["create", "delete","get"]
