---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fusion-installer
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: [ "get" ]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles"]
    verbs: ["get", "delete", "create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames:
    verbs: ["create", "get", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames:
      - "authservices.getambassador.io"
      - "consulresolvers.getambassador.io"
      - "kubernetesendpointresolvers.getambassador.io"
      - "kubernetesserviceresolvers.getambassador.io"
      - "logservices.getambassador.io"
      - "mappings.getambassador.io"
      - "modules.getambassador.io"
      - "ratelimitservices.getambassador.io"
      - "tcpmappings.getambassador.io"
      - "tlscontexts.getambassador.io"
      - "tracingservices.getambassador.io"
    verbs: ["list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtemplates", "workflowtemplates/finalizers"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]
